services:
  - type: web
    name: ojasos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python ojasos_chat_module/app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
